In [1]:
import os
import pandas as pd
import math
import matplotlib.pyplot as plt

In [2]:


Hours = [2,4,6,8,10]
Marks = [45,55,65,70,80]

df = pd.DataFrame({
        "Hours": Hours,
        "Marks": Marks
    })



In [3]:
from sklearn.linear_model import LinearRegression
import numpy as np
#use Linear Regression
modelo = LinearRegression()


In [4]:
X = df["Hours"].values.reshape(-1,1)
Y = df["Marks"].values

In [5]:
#transform
modelo.fit(X, Y)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


### Answer 1:

In [6]:
#print the values B1, B0 and R2
print("Pendiente (β₁):", modelo.coef_[0])
print("Intercepto (β₀):", modelo.intercept_)

Pendiente (β₁): 4.25
Intercepto (β₀): 37.5


### Answer 2:

In [7]:
x2 = 7
y2 = modelo.coef_[0]*x2 + modelo.intercept_
print("Y:", y2)

Y: 67.25


When x is 7, Y is 67.25

### Answer 3:

In [8]:
#predict values
Y_pred = modelo.predict(X)
df["y_pred"] = Y_pred
df["y_pred"]

0    46.0
1    54.5
2    63.0
3    71.5
4    80.0
Name: y_pred, dtype: float64

In [9]:
residuos = Y - Y_pred
df["residuos"] = residuos
df["residuos"]

0   -1.0
1    0.5
2    2.0
3   -1.5
4    0.0
Name: residuos, dtype: float64

Resudals values are very low, so values are near zero.

### Answer 4:

In [10]:
print("R²:", modelo.score(X, Y))

R²: 0.9897260273972602


The R2 es aproximately 98,9%, so predictions are highly reliable, becase R2 are too high and residuals are very small

### Answer 5:

The relationship is highly reliable because the model has a very high R
2 value and the residuals are small, indicating accurate and consistent predictions.

In [11]:
#estandar desv

X_mean = X.mean()
Y_mean = Y.mean()


In [13]:
X_lessProm = X - X_mean
Y_lessProm = Y - Y_mean

X_lessProm2 = X_lessProm**2
Y_lessProm2 = Y_lessProm**2

In [14]:
Sxx = X_lessProm2.sum()
Syy = Y_lessProm2.sum()
Sxy = X_lessProm.sum()*Y_lessProm.sum()

In [15]:
print(Sxx, Syy, Sxy)

40.0 730.0 [[ 72.  32.  -8. -28. -68.]
 [ 36.  16.  -4. -14. -34.]
 [ -0.  -0.   0.   0.   0.]
 [-36. -16.   4.  14.  34.]
 [-72. -32.   8.  28.  68.]]


In [16]:
b = Sxy/Sxx
b

array([[ 1.8 ,  0.8 , -0.2 , -0.7 , -1.7 ],
       [ 0.9 ,  0.4 , -0.1 , -0.35, -0.85],
       [-0.  , -0.  ,  0.  ,  0.  ,  0.  ],
       [-0.9 , -0.4 ,  0.1 ,  0.35,  0.85],
       [-1.8 , -0.8 ,  0.2 ,  0.7 ,  1.7 ]])

In [17]:
a = Y_mean - b*X_mean
a

array([[52.2, 58.2, 64.2, 67.2, 73.2],
       [57.6, 60.6, 63.6, 65.1, 68.1],
       [63. , 63. , 63. , 63. , 63. ],
       [68.4, 65.4, 62.4, 60.9, 57.9],
       [73.8, 67.8, 61.8, 58.8, 52.8]])

In [19]:
df["residuos_sqr"] = df["residuos"]**2
df["residuos_sqr"]

0    1.00
1    0.25
2    4.00
3    2.25
4    0.00
Name: residuos_sqr, dtype: float64

In [21]:
df["residuos_sqr"].size

5

In [23]:
o2 = df["residuos_sqr"].sum()/(df["residuos_sqr"].size - 2)
o2

np.float64(2.5)

In [24]:
o = float(o2**(1/2))
o

1.5811388300841898

In [ ]:
"""
Remembering y = 
"""